name: Network test

on: [workflow_dispatch]      

jobs:
  network:
    runs-on: ubuntu-latest
    # Uses our custom docker with r-base and miic dependencies https://hub.docker.com/repository/docker/miicteam/r-miic
    container: miicteam/r-miic

    name:    ${{ matrix.network }} test

    strategy:
      fail-fast: false
      matrix:
        network: [neuro, hemato]

    steps:
      - uses: actions/checkout@v1
      - name: miic installation
        run: R CMD INSTALL .
      - name: Network test
        run: |
          cd /tests/networks/${{ matrix.network }}
          Rscript test.R > /dev/null
